package com.khoi.lab.entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Unit tests for the DonationReceiver entity.
 * This class tests the basic functionality of the entity, including
 * constructors,
 * getters, setters, and the toString() method.
 */
public class DonationReceiverTest {

    private DonationReceiver donationReceiver;
    private static final String TEST_NAME = "John Doe";
    private static final String TEST_PHONE_NUMBER = "0123456789";

    @BeforeEach
    void setUp() {
        // Create a fresh instance of the entity for each test
        this.donationReceiver = new DonationReceiver(TEST_NAME, TEST_PHONE_NUMBER);
    }

    @Test
    void testConstructorWithValidData() {
        // Verify that the constructor correctly sets the name and phone number
        assertNotNull(donationReceiver, "DonationReceiver instance should not be null.");
        assertEquals(TEST_NAME, donationReceiver.getName(), "The name should be set correctly by the constructor.");
        assertEquals(TEST_PHONE_NUMBER, donationReceiver.getPhoneNumber(),
                "The phone number should be set correctly by the constructor.");
        // The ID should be null initially as it's generated by the database
        assertNull(donationReceiver.getId(), "The ID should be null before it is set.");
    }

    @Test
    void testGettersAndSetters() {
        // Test the ID setter and getter
        Long testId = 100L;
        donationReceiver.setId(testId);
        assertEquals(testId, donationReceiver.getId(), "The ID getter should return the value set by the setter.");

        // Test the name setter and getter
        String newName = "Jane Smith";
        donationReceiver.setName(newName);
        assertEquals(newName, donationReceiver.getName(), "The name getter should return the value set by the setter.");

        // Test the phone number setter and getter
        String newPhoneNumber = "9876543210";
        donationReceiver.setPhoneNumber(newPhoneNumber);
        assertEquals(newPhoneNumber, donationReceiver.getPhoneNumber(),
                "The phone number getter should return the value set by the setter.");
    }
}
