package com.khoi.lab.entity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Unit tests for the PasswordResetCode entity.
 * This class tests the basic functionality of the entity, including
 * constructors,
 * getters, setters, and the toString() method.
 */
public class PasswordResetCodeTest {

    private PasswordResetCode passwordResetCode;
    private static final String TEST_CODE = "RESET123";
    private static final Long TEST_ACCOUNT_ID = 456L;

    @BeforeEach
    void setUp() {
        // Create a fresh instance of the entity for each test
        this.passwordResetCode = new PasswordResetCode(TEST_CODE, TEST_ACCOUNT_ID);
    }

    @Test
    void testConstructorWithValidData() {
        // Verify that the constructor correctly sets the code and accountId
        assertNotNull(passwordResetCode, "PasswordResetCode instance should not be null.");
        assertEquals(TEST_CODE, passwordResetCode.getCode(), "The code should be set correctly by the constructor.");
        assertEquals(TEST_ACCOUNT_ID, passwordResetCode.getAccount_id(),
                "The accountId should be set correctly by the constructor.");
        // The ID should be null initially as it's generated by the database
        assertNull(passwordResetCode.getId(), "The ID should be null before it is set.");
    }

    @Test
    void testGettersAndSetters() {
        // Test the ID setter and getter
        Long testId = 1L;
        passwordResetCode.setId(testId);
        assertEquals(testId, passwordResetCode.getId(), "The ID getter should return the value set by the setter.");

        // Test the code setter and getter
        String newCode = "NEWCODE789";
        passwordResetCode.setCode(newCode);
        assertEquals(newCode, passwordResetCode.getCode(),
                "The code getter should return the value set by the setter.");

        // Test the accountId setter and getter
        Long newAccountId = 789L;
        passwordResetCode.setAccount_id(newAccountId);
        assertEquals(newAccountId, passwordResetCode.getAccount_id(),
                "The accountId getter should return the value set by the setter.");
    }
}
